title:               li-jx
tagline:             'Home Page'
url:                 https://lijianxue77.github.io/
baseurl:             ''
theme-base:          theme-base-07

# et your personal images here
head-portrait: https://s.gravatar.com/avatar/dc4bb5e468daf9796719cc2be5c125dd?s=320
shortcut-icon: /assets/icon.jpg
background-image: /assets/background.png
background-image-mobile: /assets/background-mobile.jpg
apple-touch-icon-precomposed: /assets/icon.jpg

# set nav links
nav:
  - title: 'Home'
    href: /
  - title: 'About'
    href: /about/
  - title: 'Archive'
    href: /archives/
  - title: 'Tags'
    href: /tags/

collections:
  tabs:
    output: true
    sort_by: order

permalink: /posts/:title/
readme_index:
  with_frontmatter: true
